import { Project } from "./types";

/**
 * Placeholder content, based on your real work history (Behance +
 * career report) — not invented, but not final copy either. This is
 * here so the site looks alive before Supabase is wired up. Replace
 * the images and tighten the copy via /admin whenever you're ready;
 * everything here is a solid draft, not a finished case study.
 */
export const placeholderProjects: Project[] = [
  {
    id: "ph-0",
    slug: "koma-kitchen",
    title: "Koma Kitchen",
    client: "Koma Kitchen",
    type: "Brand Identity",
    year: 2025,
    summary: "A full brand system for a kitchen concept that needed to feel warm, precise, and unmistakably its own.",
    description:
      "Full identity system for Koma Kitchen — naming support, wordmark, visual language, and application across packaging, social, and space.\n\nReplace with the real project story: the brief, the constraint that shaped it, and the one decision you're proudest of.",
    cover_image: null,
    gallery: [],
    featured: true,
    badge_color: null,
    sort_order: 0,
    published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "ph-1",
    slug: "rark-ramadan-campaign",
    title: "RARK",
    client: "Ramadan Acts of Random Kindness",
    type: "Brand Identity / Campaign System",
    year: 2026,
    summary: "A full visual system, held together across dozens of live assets, through one charity's entire Ramadan season.",
    description:
      "Two logo directions developed with written rationale — an Arabic calligraphy mark and a 'giving circle' mark — followed by a full live campaign: Ramadan, Jummah, and Eid greetings, fundraiser trackers and milestone updates, program explainers, and gratitude posts, plus a logo refinement pass partway through.\n\nThe real test of a brand system isn't the first asset, it's the fortieth — staying visually consistent (color, type, motif) across a live, fast-moving campaign without it feeling phoned in.\n\nReplace with your own note on working with RARK directly, if you want that context on the page.",
    cover_image: null,
    gallery: [],
    featured: false,
    badge_color: null,
    sort_order: 1,
    published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "ph-2",
    slug: "ten-brand-spec-ads",
    title: "Ten brands, ten ideas",
    client: "Self-initiated",
    type: "Concept Advertising",
    year: 2026,
    summary: "Spec ads for Colgate, Spotify, Starlink, Grok, Dangote, and five more — one sharp visual idea each, minimal copy.",
    description:
      "A set of concept advertisements for ten established brands (Colgate, Spotify, Starlink, Grok, Dangote, Twyford, Robb, Gino, Lontor, AKT), each built around a single visual metaphor or pun rather than product photography.\n\nThis is the idea-first side of the practice — a different muscle from a full identity system, closer to agency-style concept advertising: one strong thought, executed cleanly.\n\nReplace with the actual ten pieces, plus a line on which one you're proudest of and why.",
    cover_image: null,
    gallery: [],
    featured: false,
    badge_color: null,
    sort_order: 2,
    published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "ph-3",
    slug: "levis-spooky-rebrand",
    title: "Levi's, spooky rebrand",
    client: "Levi's (concept)",
    type: "Concept / Award-winning",
    year: 2025,
    summary: "Winner, Deestinct Halloween Rebrand Challenge (2025).",
    description:
      "A concept rebrand exploring how a legacy brand's system flexes for a seasonal moment without breaking it — a full Halloween campaign for Levi's that preserved brand equity while adapting the identity. Selected as the winning entry in the Deestinct Halloween Rebrand Challenge.\n\nReplace with your own write-up of the process, if you'd like more than the result on the page.",
    cover_image: null,
    gallery: [],
    featured: false,
    badge_color: null,
    sort_order: 3,
    published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "ph-4",
    slug: "mike-sports-apparel",
    title: "mike.",
    client: "mike.",
    type: "Brand Identity",
    year: 2025,
    summary: "A sports apparel brand that needed to look fast standing still.",
    description:
      "Full identity system for mike. — wordmark, kit graphics, and social templates built to hold up on a jersey and a phone screen equally well.\n\nReplace this with the real project story: the brief, the constraint that shaped it, and the one decision you're proudest of.",
    cover_image: null,
    gallery: [],
    featured: false,
    badge_color: null,
    sort_order: 4,
    published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "ph-5",
    slug: "five-stages-of-grief",
    title: "5 Stages of Grief",
    client: "Personal",
    type: "Editorial / Visual Exploration",
    year: 2025,
    summary: "A visual language for something nobody wants to design for.",
    description:
      "A personal, non-commercial series translating each stage of grief into its own colour, mark, and mood — sequential visual storytelling rather than a single image.\n\nReplace with your own note on why you made it — personal work is where the wit gets to be quieter.",
    cover_image: null,
    gallery: [],
    featured: false,
    badge_color: null,
    sort_order: 5,
    published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "ph-6",
    slug: "loomi-travels-social",
    title: "Loomi Travels",
    client: "Loomi Travels",
    type: "Social Media Design",
    year: 2025,
    summary: "A travel brand's feed, tightened into something worth stopping for.",
    description:
      "A social system for Loomi Travels — a grid of templates flexible enough for daily posting without ever looking like a template.\n\nReplace with the real scope: how many templates, what the brand asked for, what changed after launch.",
    cover_image: null,
    gallery: [],
    featured: false,
    badge_color: null,
    sort_order: 6,
    published: true,
    created_at: new Date().toISOString(),
  },
];
